Upgrade brew

diff --git a/share/homebrew/brew/bin/brew b/share/homebrew/brew/bin/brew
--- a/share/homebrew/brew/bin/brew
+++ b/share/homebrew/brew/bin/brew
@@ -1,14 +1,25 @@
 #!/bin/bash
-set +o posix
+
+# Fail fast with concise message when not using bash
+# Single brackets is needed here for POSIX compatibility
+# shellcheck disable=SC2292
+if [ -z "${BASH_VERSION:-}" ]
+then
+  echo "Error: Bash is required to run brew." >&2
+  exit 1
+fi
+
+set +o posix # as we are using bash now
 
 # Fail fast with concise message when cwd does not exist
-if ! [[ -d "${PWD}" ]]; then
+if ! [[ -d "${PWD}" ]]
+then
   echo "Error: The current working directory doesn't exist, cannot proceed." >&2
   exit 1
 fi
 
 quiet_cd() {
-  cd "$@" >/dev/null || return
+  cd "$@" &>/dev/null || return
 }
 
 symlink_target_directory() {
@@ -64,7 +75,7 @@ HOMEBREW_LIBRARY="${HOMEBREW_REPOSITORY}/Library"
 
 # Copy and export all HOMEBREW_* variables previously mentioned in
 # manpage or used elsewhere by Homebrew.
-for VAR in BROWSER DISPLAY EDITOR NO_COLOR PATH TMUX
+for VAR in BROWSER DISPLAY EDITOR NO_COLOR PATH TMUX DBUS_SESSION_BUS_ADDRESS
 do
   # Skip if variable value is empty.
   [[ -z "${!VAR}" ]] && continue
@@ -74,6 +85,7 @@ do
   [[ -n "${!VAR_NEW}" ]] && continue
   export "${VAR_NEW}"="${!VAR}"
 done
+unset VAR VAR_NEW
 
 export HOMEBREW_BREW_FILE
 export HOMEBREW_PREFIX
@@ -104,18 +116,21 @@ then
   PATH="/usr/bin:/bin:/usr/sbin:/sbin"
 
   FILTERED_ENV=()
+  ENV_VAR_NAMES=(
+    HOME SHELL PATH TERM TERMINFO COLUMNS DISPLAY LOGNAME USER CI SSH_AUTH_SOCK SUDO_ASKPASS
+    http_proxy https_proxy ftp_proxy no_proxy all_proxy HTTPS_PROXY FTP_PROXY ALL_PROXY
+    GITHUB_ACTIONS GITHUB_WORKSPACE GITHUB_ACTIONS_HOMEBREW_MACOS_SELF_HOSTED
+    GITHUB_REPOSITORY GITHUB_RUN_ID GITHUB_SHA GITHUB_HEAD_REF GITHUB_BASE_REF GITHUB_REF
+  )
   # Filter all but the specific variables.
-  for VAR in HOME SHELL PATH TERM TERMINFO COLUMNS DISPLAY LOGNAME USER CI SSH_AUTH_SOCK SUDO_ASKPASS \
-             http_proxy https_proxy ftp_proxy no_proxy all_proxy HTTPS_PROXY FTP_PROXY ALL_PROXY \
-             GITHUB_ACTIONS GITHUB_WORKSPACE GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED \
-             GITHUB_REPOSITORY GITHUB_RUN_ID GITHUB_SHA GITHUB_HEAD_REF GITHUB_BASE_REF GITHUB_REF \
-             "${!HOMEBREW_@}"
+  for VAR in "${ENV_VAR_NAMES[@]}" "${!HOMEBREW_@}"
   do
     # Skip if variable value is empty.
     [[ -z "${!VAR}" ]] && continue
 
-    FILTERED_ENV+=( "${VAR}=${!VAR}" )
+    FILTERED_ENV+=("${VAR}=${!VAR}")
   done
+  unset VAR ENV_VAR_NAMES
 
   exec /usr/bin/env -i "${FILTERED_ENV[@]}" /bin/bash "${HOMEBREW_LIBRARY}/Homebrew/brew.sh" "$@"
 else
